import mirrorCreator from 'mirror-creator';

export default mirrorCreator([
  'QUERY_TOGGLE',
  'ADVANCED_QUERY_UPDATE',
  'ADVANCED_HIGHLIGHT_UPDATE',
  'QUERY_RESULTS_SUCCESS',
  'QUERY_RESULTS_FAILURE',
  'LAYER_NAME_UPDATE',
  'TERMINAL_NAME_UPDATE',
  'TERMINAL_VALUE_UPDATE',
]);
